In [4]:
from bs4 import BeautifulSoup
import requests
import time
import pandas as pd
drugname = 'Remdesivir'
url = "https://go.drugbank.com/unearth/q?utf8=%E2%9C%93&query=" + drugname +"&searcher=drugs"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
items = soup.find_all('dl')
Features = []
Details = []

for category in items:
    
    Features1 = category.find_all('dt')
    Details1 = category.find_all('dd')
    for n in Features1:
        if None in (Features1):
            continue
        n1=n.text
        Features.append(n1)
    for b in Details1:
        if None in (Features1, Details1):
            continue
        b1=b.text
        Details.append(b1)

Features = pd.DataFrame(Features, columns=['Features'])
Region = pd.DataFrame(Features, columns=['Region'])
Details = pd.DataFrame(Details, columns=['Details'])
Final_list = pd.concat([Features, Details], axis=1)

In [5]:
from bs4 import BeautifulSoup
import requests
import time
import pandas as pd

In [6]:
class Web_scrapper:
    def __init__(self):
        pass
    def get_Data (self,drugs) :
        Temp_data=[]               ## to store all the records
        for drug in drugs:
            temp=[]               ## temporary record store for each drug
            url = "https://go.drugbank.com/unearth/q?utf8=%E2%9C%93&query=" + drug +"&searcher=drugs"
            response = requests.get(url)
            soup = BeautifulSoup(response.text, "html.parser")
            items = soup.find_all('dl')

            if len(items)== 0 :        ## if there is no matching record then put all the values as None
                temp.append(drug)
                for i in range(8):
                    temp.append(None)
            else :
                temp.append(items[0].find('dt', id="name").find_next('dd').text)
                temp.append(items[0].find('dt', id="description").find_next('dd').text)
                temp.append(items[0].find('dt', id="synonyms").find_next('dd').text)
                temp.append(items[0].find('dt', id="chemical-formula").find_next('dd').text)
                temp.append(items[5].find('dt', id="super-class").find_next('dd').text)
                temp.append(items[5].find('dt', id="direct-parent").find_next('dd').text)
                temp.append(items[5].find('dt', id="sub-class").find_next('dd').text)
                temp.append(items[2].find('dt', id="indication").find_next('dd').text)
                #temp.append(items[6].find('dt', id="Region").find_next('dd').text)
                Ass_c=items[2].find('dt', id="associated-conditions").find_next('dd').text
                temp.append(Ass_c.split(sep='\n'))

            Temp_data.append(temp)     ## append all the data of the drugs

        columns=['Name','Description','Synonyms','Chemical_formula','Super_Class','Direct_Parent','Sub_Class','Indication','Associated_Conditions']
        Data=pd.DataFrame(data=Temp_data,columns=columns)   
        return Data                 ## return in the form of dataframe

In [7]:
## Drugs to get information 
#drugs=['MANNITOL 2','ACYCLOVIR']

In [23]:
df1 = pd.read_csv('State_Drug_Utilization_Data_2018.csv')
df1.head()

,Utilization Type,State,Labeler Code,Product Code,Package Size,Year,Quarter,Product Name,Suppression Used,Units Reimbursed,Number of Prescriptions,Total Amount Reimbursed,Medicaid Amount Reimbursed,Non Medicaid Amount Reimbursed,Quarter Begin,Quarter Begin Date,Latitude,Longitude,Location,NDC
0,FFSU,XX,68001,132,0,2018,1,AMLODIPINE,False,810.0,23.0,433.26,427.83,5.43,1/1,01/01/2018 12:00:00 AM,NaN,NaN,NaN,68001013200
1,FFSU,XX,55292,302,1,2018,1,TRANXENE T,False,1215.0,15.0,9863.82,9860.82,3.00,1/1,01/01/2018 12:00:00 AM,NaN,NaN,NaN,55292030201
2,FFSU,XX,115,1040,1,2018,1,PROMETHAZI,False,240.0,15.0,217.36,217.36,0.00,1/1,01/01/2018 12:00:00 AM,NaN,NaN,NaN,115104001
3,FFSU,XX,68084,22,11,2018,1,NIFEDIPINE,False,40.0,20.0,75.50,75.50,0.00,1/1,01/01/2018 12:00:00 AM,NaN,NaN,NaN,68084002211
4,MCOU,XX,49884,173,9,2018,1,AMLODIPINE,False,480.0,16.0,609.19,604.19,5.00,1/1,01/01/2018 12:00:00 AM,NaN,NaN,NaN,49884017309

In [24]:
df1['Product Name'].values

array(['AMLODIPINE', 'TRANXENE T', 'PROMETHAZI', ..., 'CARBAMAZEP',
       'ZOLEDRONIC', 'ZONEGRAN 2'], dtype=object)

In [25]:
drugs=list(df1['Product Name'])

In [26]:
#drug=['NIFEDIPINE','AMLODIPINE']

In [27]:
web_scrapper=Web_scrapper()  ## create objec

In [30]:
df=web_scrapper.get_Data(drugs)  ## call function

In [31]:
df.head()   ## show data

,Name,Description,Synonyms,Chemical_formula,Super_Class,Direct_Parent,Sub_Class,Indication,Associated_Conditions
0,LEVETIRACE,None,None,None,None,None,None,None,None
1,COUGH DM E,None,None,None,None,None,None,None,None
2,Gabapentin,Gabapentin is a structural analogue of the inh...,1-(Aminomethyl)cyclohexaneacetic acidGabapenti...,C9H17NO2,Organic acids and derivatives,Gamma amino acids and derivatives,"Amino acids, peptides, and analogues","In the United States, gabapentin is officially...","[Partial-Onset Seizures, Peripheral Neuropathi..."